/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AdminUserDetailDto } from '../model/models';
import { AdminUserDto } from '../model/models';
import { AdminUserDtoPaginatedList } from '../model/models';
import { CreateAdminUserRequest } from '../model/models';
import { ProblemDetails } from '../model/models';
import { UpdateUserRoleRequest } from '../model/models';
import { UpdateUserStatusRequest } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminUsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/admin/users
     * @param role 
     * @param isActive 
     * @param emailConfirmed 
     * @param createdFrom 
     * @param createdTo 
     * @param search 
     * @param pageNumber 
     * @param pageSize 
     * @param apiVersion 
     */
    apiAdminUsersGet(role?: string, isActive?: boolean, emailConfirmed?: boolean, createdFrom?: string, createdTo?: string, search?: string, pageNumber?: number, pageSize?: number, apiVersion?: string, extraHttpRequestParams?: any): Observable<AdminUserDtoPaginatedList>;

    /**
     * 
     * 
     * @endpoint delete /api/admin/users/{id}
     * @param id 
     * @param apiVersion 
     */
    apiAdminUsersIdDelete(id: number, apiVersion?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/admin/users/{id}
     * @param id 
     * @param apiVersion 
     */
    apiAdminUsersIdGet(id: number, apiVersion?: string, extraHttpRequestParams?: any): Observable<AdminUserDetailDto>;

    /**
     * 
     * 
     * @endpoint patch /api/admin/users/{id}/role
     * @param id 
     * @param apiVersion 
     * @param updateUserRoleRequest 
     */
    apiAdminUsersIdRolePatch(id: number, apiVersion?: string, updateUserRoleRequest?: UpdateUserRoleRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint patch /api/admin/users/{id}/status
     * @param id 
     * @param apiVersion 
     * @param updateUserStatusRequest 
     */
    apiAdminUsersIdStatusPatch(id: number, apiVersion?: string, updateUserStatusRequest?: UpdateUserStatusRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/admin/users
     * @param apiVersion 
     * @param createAdminUserRequest 
     */
    apiAdminUsersPost(apiVersion?: string, createAdminUserRequest?: CreateAdminUserRequest, extraHttpRequestParams?: any): Observable<AdminUserDto>;

}
