/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuditLogDtoPaginatedList } from '../model/models';
import { ProblemDetails } from '../model/models';
import { SystemSettingDto } from '../model/models';
import { UpsertSystemSettingRequest } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminSystemServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/admin/system/audit-logs
     * @param table 
     * @param userId 
     * @param from 
     * @param to 
     * @param pageNumber 
     * @param pageSize 
     * @param apiVersion 
     */
    apiAdminSystemAuditLogsGet(table?: string, userId?: number, from?: string, to?: string, pageNumber?: number, pageSize?: number, apiVersion?: string, extraHttpRequestParams?: any): Observable<AuditLogDtoPaginatedList>;

    /**
     * 
     * 
     * @endpoint post /api/admin/system/cache/clear
     * @param apiVersion 
     */
    apiAdminSystemCacheClearPost(apiVersion?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/admin/system/settings
     * @param apiVersion 
     */
    apiAdminSystemSettingsGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<SystemSettingDto>>;

    /**
     * 
     * 
     * @endpoint get /api/admin/system/settings/{key}
     * @param key 
     * @param apiVersion 
     */
    apiAdminSystemSettingsKeyGet(key: string, apiVersion?: string, extraHttpRequestParams?: any): Observable<SystemSettingDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/system/settings/{key}
     * @param key 
     * @param apiVersion 
     * @param upsertSystemSettingRequest 
     */
    apiAdminSystemSettingsKeyPut(key: string, apiVersion?: string, upsertSystemSettingRequest?: UpsertSystemSettingRequest, extraHttpRequestParams?: any): Observable<{}>;

}
