/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DeliverySettingsDto } from '../model/models';
import { OpeningHoursDto } from '../model/models';
import { PaymentMethodsDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { RestaurantIdentityDto } from '../model/models';
import { TaxFeesDto } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RestaurantSettingsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/admin/restaurant/delivery
     * @param apiVersion 
     */
    apiAdminRestaurantDeliveryGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<DeliverySettingsDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/restaurant/delivery
     * @param apiVersion 
     * @param deliverySettingsDto 
     */
    apiAdminRestaurantDeliveryPut(apiVersion?: string, deliverySettingsDto?: DeliverySettingsDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/admin/restaurant/identity
     * @param apiVersion 
     */
    apiAdminRestaurantIdentityGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<RestaurantIdentityDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/restaurant/identity
     * @param apiVersion 
     * @param restaurantIdentityDto 
     */
    apiAdminRestaurantIdentityPut(apiVersion?: string, restaurantIdentityDto?: RestaurantIdentityDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/admin/restaurant/opening-hours
     * @param apiVersion 
     */
    apiAdminRestaurantOpeningHoursGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<OpeningHoursDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/restaurant/opening-hours
     * @param apiVersion 
     * @param openingHoursDto 
     */
    apiAdminRestaurantOpeningHoursPut(apiVersion?: string, openingHoursDto?: OpeningHoursDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/admin/restaurant/payment-methods
     * @param apiVersion 
     */
    apiAdminRestaurantPaymentMethodsGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<PaymentMethodsDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/restaurant/payment-methods
     * @param apiVersion 
     * @param paymentMethodsDto 
     */
    apiAdminRestaurantPaymentMethodsPut(apiVersion?: string, paymentMethodsDto?: PaymentMethodsDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/admin/restaurant/tax-fees
     * @param apiVersion 
     */
    apiAdminRestaurantTaxFeesGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<TaxFeesDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/restaurant/tax-fees
     * @param apiVersion 
     * @param taxFeesDto 
     */
    apiAdminRestaurantTaxFeesPut(apiVersion?: string, taxFeesDto?: TaxFeesDto, extraHttpRequestParams?: any): Observable<{}>;

}
