/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuditLogDto { 
    id?: number;
    tableName?: string | null;
    recordId?: number;
    action?: string | null;
    oldValues?: string | null;
    newValues?: string | null;
    userId?: number | null;
    createdAt?: string;
}

