/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeliverySettingsDto { 
    enabled?: boolean;
    radiusKm?: number;
    minOrder?: number;
    fee?: number;
    estimatedMinutes?: number;
}

