/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OpeningDayDto } from './openingDayDto';


export interface OpeningHoursDto { 
    days?: Array<OpeningDayDto> | null;
}

