/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DayOfWeek } from './dayOfWeek';
import { TimeRangeDto } from './timeRangeDto';


export interface OpeningDayDto { 
    dayOfWeek?: DayOfWeek;
    isClosed?: boolean;
    ranges?: Array<TimeRangeDto> | null;
}
export namespace OpeningDayDto {
}


